### ISSUE TITLE
wayland-xdg-shell-client-protocol.h not found

### ISSUE THREAD

**Issue by zezba9000** [christianrauch/wayland_window_decoration_example#1]
What dependencies do I need for "wayland-xdg-shell-client-protocol.h" ?
Your readme is missing this and I can't find online what I need to install for XDG on Ubuntu 22.04

**Comment by zezba9000** [comment]
Never mind, see this is generated. Man Wayland is a mess.

**Comment by zezba9000** [comment]
I do have to say, making this C++ was a huge mistake.
Should have used C for this example. C++ mixed with C in IDEs like vscode is very annoying to setup.

**Comment by christianrauch** [comment]
You should consider a different IDE if it cannot handle mixed C and C++ setups. Should everyone now write in C only, just because of your IDE choice?

**Comment by christianrauch** [comment]
> Never mind, see this is generated.

Correct. The language-specific bindings have to be generated from the protocol specification to support different languages. Just install the dependencies listed in the README and then `cmake -B build` and `cmake --build build` to build the project.

**Comment by zezba9000** [comment]
> You should consider a different IDE if it cannot handle mixed C and C++ setups. Should everyone now write in C only, just because of your IDE choice?

Wayland is written in C. Just makes things less hassle. I switched to cmake with CLion. vscode is a fragmented mess here.
Code::Blocks doesn't event install on Ubuntu correctly. Linux is in a sad state tbh when it comes to IDEs outside paid ones.

btw "wl_display_dispatch_pending" is getting this error after it runs a couple itterations (Ubuntu 22.04 on UM773 Lite PC):
```
listener function for opcode 2 of xdg_toplevel is NULL
```

**Comment by zezba9000** [comment]
Never mind, building in CLion runs fine then it crashes while just using cmake by itself does not.
God Linux situation is a hot mess. O well. At least I have some good example code. Thank you for making this.

**Comment by christianrauch** [comment]
> Wayland is written in C. Just makes things less hassle. I switched to cmake with CLion. vscode is a fragmented mess here.
> Code::Blocks doesn't event install on Ubuntu correctly. Linux is in a sad state tbh when it comes to IDEs outside paid ones.

Hey man, if you are just here to complain about IDEs, Wayland and my "messy" project, then please just go somewhere else to let some stream off.

I created this code to learn how to create client-side decorations on Wayland. It does not exist to please one specific person on the internet. If you don't like what it does, go somewhere else please. I am also not here to explain to you what Wayland is and how it works or how to use an IDE on Linux.

I honestly don't get your problem. The project is pretty trivial to compile and it's not the first that auto-generated the protocol bindings. Generating code is actually pretty common for protocols that support multiple languages.

Back to the topic: Wayland is a protocol with a specification in XML format. The language-specific bindings are generated from those XML files. This is e.g. how you would natively support other languages like Rust. If you want to use pre-generated source files, then just copy them from somewhere else. You then have to do this for every new version of the protocol that you want to support.

> btw "wl_display_dispatch_pending" is getting this error after it runs a couple itterations (Ubuntu 22.04 on UM773 Lite PC):
> 
> ```
> listener function for opcode 2 of xdg_toplevel is NULL
> ```

I pushed a commit that should check the protocol versions correctly and fix this.

**Comment by zezba9000** [comment]
I'm not whining about your project. Its great. I simply stated a pure C project is easier to debug in more IDEs faster without hassle (I normally dev on Windows or macOS & don't have to deal with this).

To be clear, I'm NOT attacking your project. While IMO Wayland is a pile of garbage with this XDG stuff this is not a criticism of your work (XDG reminds me of the nightmare that is OpenXR and OpenVR input protocols that are over-engineered [this also makes the API subject to runtime errors instead of compile time ones]).

I know Wayland is generating C bindings for this protocol with XML BUT again this is a very fragile system if features are changed in future Ubuntu updates or KUbuntu might be totally different. So I'm using your project to learn how XDG works & what bindings are different between Gnome and KDE etc. I'll be making a custom C# wrapper that dynamically handles multiple system bindings if there are differences & remove the need for this fragile XDG layer thats statically compiled.

**Anyway thanks for the help. Sorry for being annoying. Just using your proj to kickstart my understanding of Wayland.**

**Comment by zezba9000** [comment]
To compliment your example I've made my own that doesn't use OpenGL.
I'm also correctly handling maximize and un-maximize states which I notice yours will mess up on FYI if you drag the window into a corner snap. You're not tracking floating window states.
Also I supported both SSD & CSD.
Anyway just sharing as I drew inspiration from your implementation originally to kick-start my own test (which will be refined and ported to C#)
https://github.com/zezba9000/WaylandClientWindow/tree/master

![image](https://github.com/christianrauch/wayland_window_decoration_example/assets/1857902/c4ee1a94-f6b9-4572-992e-636c322dc26e)

**Comment by christianrauch** [comment]
Hey. Don't expect too much from this repo. This is just an example of how CSD can be implemented. It's not a plug & play library.

If you are looking for a proper implementation of decorations for Wayland, then please have a look at https://gitlab.freedesktop.org/libdecor/libdecor.
